### ISSUE TITLE
ValueError: Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by oijkn** [mac133k/yaspex#3]
When I use the metrics in Gauge, I get the following error message: 

`ValueError: Duplicated timeseries in CollectorRegistry <metric_name>`

If I comment out the line https://github.com/mac133k/yaspex/blob/master/main.py#L22, I get no more error.

**Comment by mac133k** [comment]
It could be something similar to https://github.com/prometheus/client_python/issues/468 . I will take a look shortly.

**Comment by oijkn** [comment]
To me, it seems like gunicorn sometime forks the same worker twice for a single request some times.

https://github.com/benoitc/gunicorn/issues/2391#issuecomment-678058195

**Edit:**
I tested with uWSGI and I get the same problem so I don't think it is from gunicorn.
But it remains a problem to send a double request with gunicorn !

**Workaround:**
After a few hours of debugging, I found a solution that seems to work.

When the collect is called I check if the metric name is not present in `REGISTRY._names_to_collectors`, then I store the data from `GaugeMetricFamily` in a temporary **pickle file**. And if the name of the metric is known in `REGISTRY._names_to_collectors` then I will read the content of the **pickle file** to finally return a yield of metrics.
Of course, don't forget to delete this file and also `REGISTRY.unregister(self)` after the yield.

**Test:**
When Prometheus poll the metrics, the targets appear UP but I don't see the name of the metric, it's quite strange.

**Comment by oijkn** [comment]
Finally, I switched to **FastAPI** and **Uvicorn** using **Gauge** and not _GaugeMetricFamily_.
The metrics appear properly in Prometheus and I don't see any duplicate queries anymore.

**Comment by mac133k** [comment]
I just tested YASPEx from main branch with Slurm  21.08 and gunicorn 20.1.0 on Docker using images from https://github.com/giovtorres/slurm-docker-cluster and everything worked as expected without any errors.

Please let me know and provide more details about your env if you think this issue should be investigated further, otherwise I will close it.

**Comment by oijkn** [comment]
You can close it, thank you for your reply. I managed it another way.
